from fastapi import FastAPI

from enum import Enum

app = FastAPI()


# All models available
class ModelName(str, Enum):
    pretrained = "pretrained"
    trained = "trained"


@app.get("/")
async def root():
    return {"message": "Be My Eyes API is running"}


@app.get("/inference")
async def inference(model_name: ModelName, image_url: str):
    return {"caption": "CAPTION  GENERATED BY MODEL, RESPONSE FROM THE API"}
